// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/drawer/cubit/viam_drawer_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/domain/analytics/usecase/log_delete_boat_event_use_case.dart'
    as _i8;
import 'package:viam_marine/app/domain/boat/model/viam_boat.dart' as _i4;
import 'package:viam_marine/app/domain/boat/usecase/change_boat_name_use_case.dart'
    as _i10;
import 'package:viam_marine/app/domain/boat/usecase/delete_boat_use_case.dart'
    as _i5;
import 'package:viam_marine/app/domain/boat/usecase/get_boats_use_case.dart'
    as _i2;
import 'package:viam_marine/app/domain/boat/usecase/get_current_boat_id_use_case.dart'
    as _i9;
import 'package:viam_marine/app/domain/boat/usecase/remove_current_boat_id_use_case.dart'
    as _i7;
import 'package:viam_marine/app/domain/boat/usecase/set_current_boat_id_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetBoatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBoatsUseCase extends _i1.Mock implements _i2.GetBoatsUseCase {
  MockGetBoatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamBoat>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ViamBoat>>.value(<_i4.ViamBoat>[]),
      ) as _i3.Future<List<_i4.ViamBoat>>);
}

/// A class which mocks [DeleteBoatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteBoatUseCase extends _i1.Mock implements _i5.DeleteBoatUseCase {
  MockDeleteBoatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SetCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetCurrentBoatIdUseCase extends _i1.Mock
    implements _i6.SetCurrentBoatIdUseCase {
  MockSetCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RemoveCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveCurrentBoatIdUseCase extends _i1.Mock
    implements _i7.RemoveCurrentBoatIdUseCase {
  MockRemoveCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LogDeleteBoatEventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogDeleteBoatEventUseCase extends _i1.Mock
    implements _i8.LogDeleteBoatEventUseCase {
  MockLogDeleteBoatEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? id,
    required String? name,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #id: id,
            #name: name,
            #address: address,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentBoatIdUseCase extends _i1.Mock
    implements _i9.GetCurrentBoatIdUseCase {
  MockGetCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ChangeBoatNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangeBoatNameUseCase extends _i1.Mock
    implements _i10.ChangeBoatNameUseCase {
  MockChangeBoatNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? id,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #id: id,
            #name: name,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
