// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/domain/analytics/usecase/log_add_boat_event_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/analytics/service/analytics_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i2.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logOpenAppEvent() => (super.noSuchMethod(
        Invocation.method(
          #logOpenAppEvent,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> logAddBoatEvent({
    required String? id,
    required String? name,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAddBoatEvent,
          [],
          {
            #id: id,
            #name: name,
            #address: address,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> logDeleteBoatEvent({
    required String? id,
    required String? name,
    required String? address,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDeleteBoatEvent,
          [],
          {
            #id: id,
            #name: name,
            #address: address,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
