// Mocks generated by Mockito 5.4.2 from annotations
// in viam_marine/test/unit_test/data/movement/service/movement_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/data/movement/data_source/movement_sdk_data_source.dart'
    as _i4;
import 'package:viam_marine/data/movement/model/compass_heading_dto.dart'
    as _i3;
import 'package:viam_marine/domain/service_base/broadcaster/token_expired_broadcaster.dart'
    as _i6;
import 'package:viam_sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVector3_1 extends _i1.SmartFake implements _i2.Vector3 {
  _FakeVector3_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompassHeadingDto_2 extends _i1.SmartFake
    implements _i3.CompassHeadingDto {
  _FakeCompassHeadingDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ViamAppMovementSdkDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppMovementSdkDataSource extends _i1.Mock
    implements _i4.ViamAppMovementSdkDataSource {
  MockViamAppMovementSdkDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Position> getPosition(_i2.ResourceName? resourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [resourceName],
        ),
        returnValue: _i5.Future<_i2.Position>.value(_FakePosition_0(
          this,
          Invocation.method(
            #getPosition,
            [resourceName],
          ),
        )),
      ) as _i5.Future<_i2.Position>);
  @override
  _i5.Future<_i2.Vector3> getLinearVelocity(_i2.ResourceName? resourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearVelocity,
          [resourceName],
        ),
        returnValue: _i5.Future<_i2.Vector3>.value(_FakeVector3_1(
          this,
          Invocation.method(
            #getLinearVelocity,
            [resourceName],
          ),
        )),
      ) as _i5.Future<_i2.Vector3>);
  @override
  _i5.Future<_i3.CompassHeadingDto> getCompassHeading(
          _i2.ResourceName? resourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompassHeading,
          [resourceName],
        ),
        returnValue:
            _i5.Future<_i3.CompassHeadingDto>.value(_FakeCompassHeadingDto_2(
          this,
          Invocation.method(
            #getCompassHeading,
            [resourceName],
          ),
        )),
      ) as _i5.Future<_i3.CompassHeadingDto>);
}

/// A class which mocks [TokenExpiredBroadcaster].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenExpiredBroadcaster extends _i1.Mock
    implements _i6.TokenExpiredBroadcaster {
  MockTokenExpiredBroadcaster() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.TokenExpiredEvent> getRefreshStream() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshStream,
          [],
        ),
        returnValue: _i5.Stream<_i6.TokenExpiredEvent>.empty(),
      ) as _i5.Stream<_i6.TokenExpiredEvent>);
  @override
  void notifyRefreshStream(_i6.TokenExpiredEvent? event) => super.noSuchMethod(
        Invocation.method(
          #notifyRefreshStream,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}
