name: viam_marine
description: DOR Project created by DOR CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  intl: 0.17.0
  auto_route: 5.0.2
  json_serializable: 6.5.2
  json_annotation: 4.7.0
  provider: 6.0.4
  fimber_io: 0.6.6
  get_it: 7.2.0
  dio: 4.0.6
  flutter_secure_storage: 5.1.2
  flutter_device_type: 0.4.0
  injectable: 1.5.3
  collection: 1.16.0
  freezed: 2.2.0
  freezed_annotation: 2.2.0
  mockito: 5.3.2
  equatable: 2.0.5
  retrofit: 3.3.1
  firebase_core: 1.24.0
  firebase_crashlytics: 2.9.0
  grpc: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  bloc_test: 9.1.0
  auto_route_generator: 5.0.2
  injectable_generator: 1.5.4
  retrofit_generator: 4.2.0
  build_runner: 2.3.0
  flutter_gen_runner: 5.0.3



flutter:
  uses-material-design: true
  assets:
  - assets/images/svg/icons/
  - assets/images/illustrations/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Thin.ttf
    - asset: assets/fonts/Inter-ExtraLight.ttf
    - asset: assets/fonts/Inter-Light.ttf
    - asset: assets/fonts/Inter-Medium.ttf
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-SemiBold.ttf
    - asset: assets/fonts/Inter-Bold.ttf
    - asset: assets/fonts/Inter-ExtraBold.ttf
    - asset: assets/fonts/Inter-Black.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en

flutter_gen: 
  output: lib/generated/