// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/sensor/service/sensor_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/data/resource/mapper/viam_app_resource_name_to_viam_resource_name_mapper.dart'
    as _i6;
import 'package:viam_marine/data/sensor/data_source/sensor_api_data_source.dart'
    as _i4;
import 'package:viam_marine/data/sensor/mapper/viam_sensor_readings_to_viam_app_sensor_readings.dart'
    as _i8;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart'
    as _i7;
import 'package:viam_marine/domain/sensor/model/viam_app_sensor_readings.dart'
    as _i3;
import 'package:viam_sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViamResourceName_0 extends _i1.SmartFake
    implements _i2.ViamResourceName {
  _FakeViamResourceName_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViamAppSensorReadings_1 extends _i1.SmartFake
    implements _i3.ViamAppSensorReadings {
  _FakeViamAppSensorReadings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SensorDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorDataSource extends _i1.Mock implements _i4.SensorDataSource {
  MockSensorDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ViamSensorReadings>> getSensorData(
          List<_i2.ViamResourceName>? resourceNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensorData,
          [resourceNames],
        ),
        returnValue: _i5.Future<List<_i2.ViamSensorReadings>>.value(
            <_i2.ViamSensorReadings>[]),
      ) as _i5.Future<List<_i2.ViamSensorReadings>>);
}

/// A class which mocks [ViamAppResourceNameToViamResourceNameMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppResourceNameToViamResourceNameMapper extends _i1.Mock
    implements _i6.ViamAppResourceNameToViamResourceNameMapper {
  MockViamAppResourceNameToViamResourceNameMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ViamResourceName call(_i7.ViamAppResourceName? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [dto],
        ),
        returnValue: _FakeViamResourceName_0(
          this,
          Invocation.method(
            #call,
            [dto],
          ),
        ),
      ) as _i2.ViamResourceName);
}

/// A class which mocks [ViamSensorReadingsToViamAppSensorReadingsMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamSensorReadingsToViamAppSensorReadingsMapper extends _i1.Mock
    implements _i8.ViamSensorReadingsToViamAppSensorReadingsMapper {
  MockViamSensorReadingsToViamAppSensorReadingsMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ViamAppSensorReadings call(_i2.ViamSensorReadings? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [dto],
        ),
        returnValue: _FakeViamAppSensorReadings_1(
          this,
          Invocation.method(
            #call,
            [dto],
          ),
        ),
      ) as _i3.ViamAppSensorReadings);
}
