// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/sensor/service/sensor_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/data/sensor/data_source/sensor_api_data_source.dart'
    as _i3;
import 'package:viam_marine/data/sensor/model/sensor_readings_dto.dart' as _i2;
import 'package:viam_marine/domain/service_base/broadcaster/token_expired_broadcaster.dart'
    as _i6;
import 'package:viam_sdk/viam_sdk.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSensorReadingsDto_0 extends _i1.SmartFake
    implements _i2.SensorReadingsDto {
  _FakeSensorReadingsDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SensorDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorDataSource extends _i1.Mock implements _i3.SensorDataSource {
  MockSensorDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SensorReadingsDto> getSensorData(
          _i5.ViamResourceName? resourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensorData,
          [resourceName],
        ),
        returnValue:
            _i4.Future<_i2.SensorReadingsDto>.value(_FakeSensorReadingsDto_0(
          this,
          Invocation.method(
            #getSensorData,
            [resourceName],
          ),
        )),
      ) as _i4.Future<_i2.SensorReadingsDto>);
}

/// A class which mocks [TokenExpiredBroadcaster].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenExpiredBroadcaster extends _i1.Mock
    implements _i6.TokenExpiredBroadcaster {
  MockTokenExpiredBroadcaster() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.TokenExpiredEvent> getRefreshStream() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshStream,
          [],
        ),
        returnValue: _i4.Stream<_i6.TokenExpiredEvent>.empty(),
      ) as _i4.Stream<_i6.TokenExpiredEvent>);
  @override
  void notifyRefreshStream(_i6.TokenExpiredEvent? event) => super.noSuchMethod(
        Invocation.method(
          #notifyRefreshStream,
          [event],
        ),
        returnValueForMissingStub: null,
      );
}
