// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/boat/service/boat_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/boat/model/viam_boat.dart' as _i4;
import 'package:viam_marine/domain/boat/store/boat_box.dart' as _i2;
import 'package:viam_marine/domain/boat/store/current_boat_store.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BoatBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoatBox extends _i1.Mock implements _i2.BoatBox {
  MockBoatBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamBoat>> read() => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ViamBoat>>.value(<_i4.ViamBoat>[]),
      ) as _i3.Future<List<_i4.ViamBoat>>);
  @override
  _i3.Future<bool> containsKey({required String? key}) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> write({
    required String? key,
    required _i4.ViamBoat? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> delete({required String? key}) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CurrentBoatStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentBoatStore extends _i1.Mock implements _i5.CurrentBoatStore {
  MockCurrentBoatStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setCurrentBoatId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentBoatId,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> removeCurrentBoatId() => (super.noSuchMethod(
        Invocation.method(
          #removeCurrentBoatId,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
