// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/injectable/grpc_client_injectable/grpc_client_injectable.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:grpc/src/client/call.dart' as _i4;
import 'package:grpc/src/client/connection.dart' as _i3;
import 'package:grpc/src/client/http2_channel.dart' as _i5;
import 'package:grpc/src/client/method.dart' as _i7;
import 'package:grpc/src/client/options.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeObject_0 extends _i1.SmartFake implements Object {
  _FakeObject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelOptions_1 extends _i1.SmartFake
    implements _i2.ChannelOptions {
  _FakeChannelOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientConnection_2 extends _i1.SmartFake
    implements _i3.ClientConnection {
  _FakeClientConnection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_3<Q, R> extends _i1.SmartFake
    implements _i4.ClientCall<Q, R> {
  _FakeClientCall_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClientChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientChannel extends _i1.Mock implements _i5.ClientChannel {
  MockClientChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Object get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _FakeObject_0(
          this,
          Invocation.getter(#host),
        ),
      ) as Object);
  @override
  int get port => (super.noSuchMethod(
        Invocation.getter(#port),
        returnValue: 0,
      ) as int);
  @override
  _i2.ChannelOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeChannelOptions_1(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.ChannelOptions);
  @override
  _i3.ClientConnection createConnection() => (super.noSuchMethod(
        Invocation.method(
          #createConnection,
          [],
        ),
        returnValue: _FakeClientConnection_2(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
      ) as _i3.ClientConnection);
  @override
  _i6.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<_i3.ClientConnection> getConnection() => (super.noSuchMethod(
        Invocation.method(
          #getConnection,
          [],
        ),
        returnValue:
            _i6.Future<_i3.ClientConnection>.value(_FakeClientConnection_2(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
      ) as _i6.Future<_i3.ClientConnection>);
  @override
  _i4.ClientCall<Q, R> createCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests,
    _i4.CallOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCall,
          [
            method,
            requests,
            options,
          ],
        ),
        returnValue: _FakeClientCall_3<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
      ) as _i4.ClientCall<Q, R>);
}
