// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/domain/camera/usecase/get_camera_data_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/domain/camera/model/viam_app_camera_data.dart'
    as _i2;
import 'package:viam_marine/app/domain/camera/service/camera_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViamAppCameraData_0 extends _i1.SmartFake
    implements _i2.ViamAppCameraData {
  _FakeViamAppCameraData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ViamAppCameraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppCameraService extends _i1.Mock
    implements _i3.ViamAppCameraService {
  MockViamAppCameraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ViamAppCameraData> getCameraData(String? cameraName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCameraData,
          [cameraName],
        ),
        returnValue:
            _i4.Future<_i2.ViamAppCameraData>.value(_FakeViamAppCameraData_0(
          this,
          Invocation.method(
            #getCameraData,
            [cameraName],
          ),
        )),
      ) as _i4.Future<_i2.ViamAppCameraData>);
}
