// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/add_boat/cubit/add_boat_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i8;
import 'package:uuid/uuid.dart' as _i2;
import 'package:viam_marine/app/domain/boat/usecase/add_new_boat_use_case.dart'
    as _i3;
import 'package:viam_marine/app/domain/boat/usecase/check_connection_use_case.dart'
    as _i5;
import 'package:viam_marine/app/domain/boat/usecase/set_current_boat_id_use_case.dart'
    as _i6;
import 'package:viam_marine/app/domain/permissions/usecase/get_camera_permission_status_use_case.dart'
    as _i7;
import 'package:viam_marine/app/domain/permissions/usecase/request_camera_permission_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUuidValue_0 extends _i1.SmartFake implements _i2.UuidValue {
  _FakeUuidValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddNewBoatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewBoatUseCase extends _i1.Mock implements _i3.AddNewBoatUseCase {
  MockAddNewBoatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call({
    required String? id,
    required String? name,
    required String? address,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #id: id,
            #name: name,
            #address: address,
            #secret: secret,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [CheckConnectionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckConnectionUseCase extends _i1.Mock
    implements _i5.CheckConnectionUseCase {
  MockCheckConnectionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(
    String? address,
    String? secret,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            address,
            secret,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SetCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetCurrentBoatIdUseCase extends _i1.Mock
    implements _i6.SetCurrentBoatIdUseCase {
  MockSetCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GetCameraPermissionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCameraPermissionStatusUseCase extends _i1.Mock
    implements _i7.GetCameraPermissionStatusUseCase {
  MockGetCameraPermissionStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.PermissionStatus> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i8.PermissionStatus>.value(_i8.PermissionStatus.denied),
      ) as _i4.Future<_i8.PermissionStatus>);
}

/// A class which mocks [RequestCameraPermissionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestCameraPermissionUseCase extends _i1.Mock
    implements _i9.RequestCameraPermissionUseCase {
  MockRequestCameraPermissionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.PermissionStatus> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i8.PermissionStatus>.value(_i8.PermissionStatus.denied),
      ) as _i4.Future<_i8.PermissionStatus>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i2.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v1,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);
  @override
  _i2.UuidValue v1obj({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v1obj,
          [],
          {#options: options},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v1obj,
            [],
            {#options: options},
          ),
        ),
      ) as _i2.UuidValue);
  @override
  String v4({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v4,
          [],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4buffer,
          [buffer],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);
  @override
  _i2.UuidValue v4obj({Map<String, dynamic>? options}) => (super.noSuchMethod(
        Invocation.method(
          #v4obj,
          [],
          {#options: options},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v4obj,
            [],
            {#options: options},
          ),
        ),
      ) as _i2.UuidValue);
  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5,
          [
            namespace,
            name,
          ],
          {#options: options},
        ),
        returnValue: '',
      ) as String);
  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5buffer,
          [
            namespace,
            name,
            buffer,
          ],
          {
            #options: options,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);
  @override
  _i2.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5obj,
          [
            namespace,
            name,
          ],
          {#options: options},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v5obj,
            [
              namespace,
              name,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.UuidValue);
}
