// Mocks generated by Mockito 5.4.2 from annotations
// in viam_marine/test/unit_test/presentation/page/main/cubit/main_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/auth/usecase/get_token_or_null_use_case.dart'
    as _i4;
import 'package:viam_marine/domain/clear_cache/use_case/clear_cache_use_case.dart'
    as _i8;
import 'package:viam_marine/domain/data_viam/use_case/clear_cached_data_use_case.dart'
    as _i11;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart'
    as _i3;
import 'package:viam_marine/domain/resource/usecase/get_resource_names_use_case.dart'
    as _i2;
import 'package:viam_marine/domain/robot_manager/use_case/check_connection_use_case.dart'
    as _i10;
import 'package:viam_marine/domain/robot_manager/use_case/connect_to_robot_use_case.dart'
    as _i9;
import 'package:viam_marine/domain/service_base/broadcaster/token_expired_broadcaster.dart'
    as _i7;
import 'package:viam_marine/domain/service_base/use_case/subscribe_to_token_expired_stream_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetResourceNamesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetResourceNamesUseCase extends _i1.Mock
    implements _i2.GetResourceNamesUseCase {
  MockGetResourceNamesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ViamAppResourceName> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: <_i3.ViamAppResourceName>[],
      ) as List<_i3.ViamAppResourceName>);
}

/// A class which mocks [GetTokenOrNullUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTokenOrNullUseCase extends _i1.Mock
    implements _i4.GetTokenOrNullUseCase {
  MockGetTokenOrNullUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [SubscribeToTokenExpiredStreamUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscribeToTokenExpiredStreamUseCase extends _i1.Mock
    implements _i6.SubscribeToTokenExpiredStreamUseCase {
  MockSubscribeToTokenExpiredStreamUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i7.TokenExpiredEvent> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Stream<_i7.TokenExpiredEvent>.empty(),
      ) as _i5.Stream<_i7.TokenExpiredEvent>);
}

/// A class which mocks [ClearCacheUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCacheUseCase extends _i1.Mock implements _i8.ClearCacheUseCase {
  MockClearCacheUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ConnectToRobotUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectToRobotUseCase extends _i1.Mock
    implements _i9.ConnectToRobotUseCase {
  MockConnectToRobotUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required String? url,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #url: url,
            #secret: secret,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.FutureOr<void> checkExpiredToken(
          _i5.FutureOr<void> Function()? methodCall) =>
      (super.noSuchMethod(Invocation.method(
        #checkExpiredToken,
        [methodCall],
      )) as _i5.FutureOr<void>);
}

/// A class which mocks [CheckConnectionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckConnectionUseCase extends _i1.Mock
    implements _i10.CheckConnectionUseCase {
  MockCheckConnectionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.FutureOr<void> checkExpiredToken(
          _i5.FutureOr<void> Function()? methodCall) =>
      (super.noSuchMethod(Invocation.method(
        #checkExpiredToken,
        [methodCall],
      )) as _i5.FutureOr<void>);
}

/// A class which mocks [ClearCachedDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCachedDataUseCase extends _i1.Mock
    implements _i11.ClearCachedDataUseCase {
  MockClearCachedDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
