// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/main/cubit/main_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/clear_cache/use_case/clear_cache_use_case.dart'
    as _i9;
import 'package:viam_marine/domain/resource/model/resource_filters.dart' as _i5;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart'
    as _i4;
import 'package:viam_marine/domain/resource/usecase/get_resource_names_use_case.dart'
    as _i2;
import 'package:viam_marine/domain/service_base/broadcaster/token_expired_broadcaster.dart'
    as _i8;
import 'package:viam_marine/domain/service_base/use_case/subscribe_to_token_expired_stream_use_case.dart'
    as _i7;
import 'package:viam_marine/domain/viam/model/robot_address_config.dart'
    as _i12;
import 'package:viam_marine/domain/viam/usecase/connect_to_robot_use_case.dart'
    as _i10;
import 'package:viam_marine/domain/viam/usecase/get_robot_address_use_case.dart'
    as _i11;
import 'package:viam_marine/domain/viam/usecase/get_token_or_null_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetResourceNamesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetResourceNamesUseCase extends _i1.Mock
    implements _i2.GetResourceNamesUseCase {
  MockGetResourceNamesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamAppResourceName>> call(
    _i5.ViamAppResourceSubtypeFilter? subtype,
    _i5.ViamAppResourceNameFilter? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            subtype,
            name,
          ],
        ),
        returnValue: _i3.Future<List<_i4.ViamAppResourceName>>.value(
            <_i4.ViamAppResourceName>[]),
      ) as _i3.Future<List<_i4.ViamAppResourceName>>);
}

/// A class which mocks [GetTokenOrNullUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTokenOrNullUseCase extends _i1.Mock
    implements _i6.GetTokenOrNullUseCase {
  MockGetTokenOrNullUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [SubscribeToTokenExpiredStreamUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscribeToTokenExpiredStreamUseCase extends _i1.Mock
    implements _i7.SubscribeToTokenExpiredStreamUseCase {
  MockSubscribeToTokenExpiredStreamUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i8.TokenExpiredEvent> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Stream<_i8.TokenExpiredEvent>.empty(),
      ) as _i3.Stream<_i8.TokenExpiredEvent>);
}

/// A class which mocks [ClearCacheUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCacheUseCase extends _i1.Mock implements _i9.ClearCacheUseCase {
  MockClearCacheUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ConnectToRobotUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectToRobotUseCase extends _i1.Mock
    implements _i10.ConnectToRobotUseCase {
  MockConnectToRobotUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? url,
    required int? port,
    required bool? secure,
    required bool? disableWebRtc,
    String? secret,
    String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #url: url,
            #port: port,
            #secure: secure,
            #disableWebRtc: disableWebRtc,
            #secret: secret,
            #accessToken: accessToken,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetRobotAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRobotAddressUseCase extends _i1.Mock
    implements _i11.GetRobotAddressUseCase {
  MockGetRobotAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call(_i12.RobotAddressConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [config],
        ),
        returnValue: '',
      ) as String);
}
