name: viam_marine
description: DOR Project created by DOR CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: 3.7.11

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  intl: 0.17.0
  auto_route: 5.0.2
  provider: 6.0.4
  fimber_io: 0.6.6
  get_it: 7.2.0
  dio: 4.0.6
  flutter_device_type: 0.4.0
  injectable: 1.5.3
  collection: 1.17.0
  freezed: 2.2.0
  freezed_annotation: 2.2.0
  mockito: 5.3.2
  equatable: 2.0.5
  retrofit: 3.3.1
  firebase_core: 2.4.1
  firebase_crashlytics: 3.0.9
  firebase_analytics: 10.1.0
  grpc: 3.1.0
  protobuf: 2.1.0
  sleek_circular_slider: 2.0.1
  google_maps_flutter: 2.2.1
  flutter_map: 3.0.0
  flutter_staggered_grid_view: 0.6.2
  flutter_svg: 1.1.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  uuid: 3.0.7
  shared_preferences: 2.0.15
  mobile_scanner: 2.1.0
  permission_handler: 10.2.0
  flutter_webrtc: 0.9.18
  webview_flutter: 3.0.4
  image_picker: 0.8.6+4
  file_picker: 5.2.5
  auth0_flutter: 1.1.0
  graphic: ^2.0.3
  viam_sdk:
    git: git@github.com:DroidsOnRoids/viam-sdk-flutter.git
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  bloc_test: 9.1.0
  auto_route_generator: 5.0.2
  injectable_generator: 1.5.4
  retrofit_generator: 4.2.0
  build_runner: 2.3.0
  flutter_gen_runner: 5.0.3
  hive_generator: 1.1.3
  flutter_launcher_icons: 0.12.0



flutter:
  uses-material-design: true
  assets:
  - assets/images/svg/icons/
  - assets/images/illustrations/
  - assets/images/illustrations/background/
  - assets/images/illustrations/placeholder/
  - assets/images/illustrations/splash/
  - assets/images/illustrations/boat/
  fonts:
  - family: Outfit
    fonts:
    - asset: assets/fonts/Outfit-Black.ttf
    - asset: assets/fonts/Outfit-Bold.ttf
    - asset: assets/fonts/Outfit-Light.ttf
    - asset: assets/fonts/Outfit-Medium.ttf
    - asset: assets/fonts/Outfit-Regular.ttf
    - asset: assets/fonts/Outfit-Thin.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter_gen: 
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  image_path: "assets/images/illustrations/app_icon_full.png"
  adaptive_icon_background: "assets/images/illustrations/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/illustrations/app_icon_foreground.png"