// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/dashboard/cubit/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/domain/boat/model/viam_boat.dart' as _i7;
import 'package:viam_marine/app/domain/boat/service/boat_service.dart' as _i6;
import 'package:viam_marine/app/domain/resource/model/resource_filters.dart'
    as _i5;
import 'package:viam_marine/app/domain/resource/model/viam_app_resource_name.dart'
    as _i4;
import 'package:viam_marine/app/domain/resource/service/resource_service_impl.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ResourceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockResourceService extends _i1.Mock implements _i2.ResourceService {
  MockResourceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamAppResourceName>> getResourceNames({
    _i5.ViamAppResourceSubtypeFilter? subtype,
    _i5.ViamAppResourceNameFilter? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResourceNames,
          [],
          {
            #subtype: subtype,
            #name: name,
          },
        ),
        returnValue: _i3.Future<List<_i4.ViamAppResourceName>>.value(
            <_i4.ViamAppResourceName>[]),
      ) as _i3.Future<List<_i4.ViamAppResourceName>>);
}

/// A class which mocks [BoatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoatService extends _i1.Mock implements _i6.BoatService {
  MockBoatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.ViamBoat>> getBoats() => (super.noSuchMethod(
        Invocation.method(
          #getBoats,
          [],
        ),
        returnValue: _i3.Future<List<_i7.ViamBoat>>.value(<_i7.ViamBoat>[]),
      ) as _i3.Future<List<_i7.ViamBoat>>);
  @override
  _i3.Future<void> addNewBoat({
    required String? id,
    required String? name,
    required String? address,
    required String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNewBoat,
          [],
          {
            #id: id,
            #name: name,
            #address: address,
            #secret: secret,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setCurrentBoatId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentBoatId,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> checkConnection(
    String? address,
    String? secret,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnection,
          [
            address,
            secret,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteBoat(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBoat,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> removeCurrentBoatId() => (super.noSuchMethod(
        Invocation.method(
          #removeCurrentBoatId,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
