// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/dashboard/cubit/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/domain/boat/model/viam_boat.dart' as _i7;
import 'package:viam_marine/app/domain/boat/usecase/get_boats_use_case.dart'
    as _i6;
import 'package:viam_marine/app/domain/boat/usecase/get_current_boat_id_use_case.dart'
    as _i8;
import 'package:viam_marine/app/domain/resource/model/resource_filters.dart'
    as _i5;
import 'package:viam_marine/app/domain/resource/model/viam_app_resource_name.dart'
    as _i4;
import 'package:viam_marine/app/domain/resource/service/resource_service_impl.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ResourceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockResourceService extends _i1.Mock implements _i2.ResourceService {
  MockResourceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamAppResourceName>> getResourceNames({
    _i5.ViamAppResourceSubtypeFilter? subtype,
    _i5.ViamAppResourceNameFilter? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResourceNames,
          [],
          {
            #subtype: subtype,
            #name: name,
          },
        ),
        returnValue: _i3.Future<List<_i4.ViamAppResourceName>>.value(
            <_i4.ViamAppResourceName>[]),
      ) as _i3.Future<List<_i4.ViamAppResourceName>>);
}

/// A class which mocks [GetBoatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBoatsUseCase extends _i1.Mock implements _i6.GetBoatsUseCase {
  MockGetBoatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.ViamBoat>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i7.ViamBoat>>.value(<_i7.ViamBoat>[]),
      ) as _i3.Future<List<_i7.ViamBoat>>);
}

/// A class which mocks [GetCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentBoatIdUseCase extends _i1.Mock
    implements _i8.GetCurrentBoatIdUseCase {
  MockGetCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }
}
