// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/sdk/src/test/unit_test/mocks/service_clients_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/sdk/src/gen/common/v1/common.pb.dart' as _i6;
import 'package:viam_marine/sdk/src/gen/component/movementsensor/v1/movementsensor.pb.dart'
    as _i5;
import 'package:viam_marine/sdk/src/gen/component/movementsensor/v1/movementsensor.pbgrpc.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseFuture_0<R> extends _i1.SmartFake
    implements _i2.ResponseFuture<R> {
  _FakeResponseFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_1<Q, R> extends _i1.SmartFake
    implements _i3.ClientCall<Q, R> {
  _FakeClientCall_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_2<R> extends _i1.SmartFake
    implements _i2.ResponseStream<R> {
  _FakeResponseStream_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovementSensorServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovementSensorServiceClient extends _i1.Mock
    implements _i4.MovementSensorServiceClient {
  MockMovementSensorServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i5.GetLinearVelocityResponse> getLinearVelocity(
    _i5.GetLinearVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetLinearVelocityResponse>(
          this,
          Invocation.method(
            #getLinearVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetLinearVelocityResponse>);
  @override
  _i2.ResponseFuture<_i5.GetAngularVelocityResponse> getAngularVelocity(
    _i5.GetAngularVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAngularVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetAngularVelocityResponse>(
          this,
          Invocation.method(
            #getAngularVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetAngularVelocityResponse>);
  @override
  _i2.ResponseFuture<_i5.GetCompassHeadingResponse> getCompassHeading(
    _i5.GetCompassHeadingRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompassHeading,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetCompassHeadingResponse>(
          this,
          Invocation.method(
            #getCompassHeading,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetCompassHeadingResponse>);
  @override
  _i2.ResponseFuture<_i5.GetOrientationResponse> getOrientation(
    _i5.GetOrientationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrientation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetOrientationResponse>(
          this,
          Invocation.method(
            #getOrientation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetOrientationResponse>);
  @override
  _i2.ResponseFuture<_i5.GetPositionResponse> getPosition(
    _i5.GetPositionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetPositionResponse>(
          this,
          Invocation.method(
            #getPosition,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetPositionResponse>);
  @override
  _i2.ResponseFuture<_i5.GetPropertiesResponse> getProperties(
    _i5.GetPropertiesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetPropertiesResponse>(
          this,
          Invocation.method(
            #getProperties,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetPropertiesResponse>);
  @override
  _i2.ResponseFuture<_i5.GetAccuracyResponse> getAccuracy(
    _i5.GetAccuracyRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccuracy,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetAccuracyResponse>(
          this,
          Invocation.method(
            #getAccuracy,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetAccuracyResponse>);
  @override
  _i2.ResponseFuture<_i5.GetLinearAccelerationResponse> getLinearAcceleration(
    _i5.GetLinearAccelerationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearAcceleration,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i5.GetLinearAccelerationResponse>(
          this,
          Invocation.method(
            #getLinearAcceleration,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i5.GetLinearAccelerationResponse>);
  @override
  _i2.ResponseFuture<_i6.DoCommandResponse> doCommand(
    _i6.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i7.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i7.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}
