// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/sdk/src/test/unit_test/mocks/service_clients_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:grpc/src/client/channel.dart' as _i18;
import 'package:grpc/src/client/connection.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/sdk/src/gen/common/v1/common.pb.dart' as _i7;
import 'package:viam_marine/sdk/src/gen/component/camera/v1/camera.pb.dart'
    as _i14;
import 'package:viam_marine/sdk/src/gen/component/camera/v1/camera.pbgrpc.dart'
    as _i13;
import 'package:viam_marine/sdk/src/gen/component/movementsensor/v1/movementsensor.pb.dart'
    as _i6;
import 'package:viam_marine/sdk/src/gen/component/movementsensor/v1/movementsensor.pbgrpc.dart'
    as _i5;
import 'package:viam_marine/sdk/src/gen/google/api/httpbody.pb.dart' as _i15;
import 'package:viam_marine/sdk/src/gen/proto/stream/v1/stream.pb.dart' as _i17;
import 'package:viam_marine/sdk/src/gen/proto/stream/v1/stream.pbgrpc.dart'
    as _i16;
import 'package:viam_marine/sdk/src/gen/robot/v1/robot.pb.dart' as _i10;
import 'package:viam_marine/sdk/src/gen/robot/v1/robot.pbgrpc.dart' as _i9;
import 'package:viam_marine/sdk/src/gen/service/sensors/v1/sensors.pb.dart'
    as _i12;
import 'package:viam_marine/sdk/src/gen/service/sensors/v1/sensors.pbgrpc.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseFuture_0<R> extends _i1.SmartFake
    implements _i2.ResponseFuture<R> {
  _FakeResponseFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_1<Q, R> extends _i1.SmartFake
    implements _i3.ClientCall<Q, R> {
  _FakeClientCall_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_2<R> extends _i1.SmartFake
    implements _i2.ResponseStream<R> {
  _FakeResponseStream_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientConnection_3 extends _i1.SmartFake
    implements _i4.ClientConnection {
  _FakeClientConnection_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovementSensorServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovementSensorServiceClient extends _i1.Mock
    implements _i5.MovementSensorServiceClient {
  MockMovementSensorServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i6.GetLinearVelocityResponse> getLinearVelocity(
    _i6.GetLinearVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetLinearVelocityResponse>(
          this,
          Invocation.method(
            #getLinearVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetLinearVelocityResponse>);
  @override
  _i2.ResponseFuture<_i6.GetAngularVelocityResponse> getAngularVelocity(
    _i6.GetAngularVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAngularVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetAngularVelocityResponse>(
          this,
          Invocation.method(
            #getAngularVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetAngularVelocityResponse>);
  @override
  _i2.ResponseFuture<_i6.GetCompassHeadingResponse> getCompassHeading(
    _i6.GetCompassHeadingRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompassHeading,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetCompassHeadingResponse>(
          this,
          Invocation.method(
            #getCompassHeading,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetCompassHeadingResponse>);
  @override
  _i2.ResponseFuture<_i6.GetOrientationResponse> getOrientation(
    _i6.GetOrientationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrientation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetOrientationResponse>(
          this,
          Invocation.method(
            #getOrientation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetOrientationResponse>);
  @override
  _i2.ResponseFuture<_i6.GetPositionResponse> getPosition(
    _i6.GetPositionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetPositionResponse>(
          this,
          Invocation.method(
            #getPosition,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetPositionResponse>);
  @override
  _i2.ResponseFuture<_i6.GetPropertiesResponse> getProperties(
    _i6.GetPropertiesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetPropertiesResponse>(
          this,
          Invocation.method(
            #getProperties,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetPropertiesResponse>);
  @override
  _i2.ResponseFuture<_i6.GetAccuracyResponse> getAccuracy(
    _i6.GetAccuracyRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccuracy,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetAccuracyResponse>(
          this,
          Invocation.method(
            #getAccuracy,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetAccuracyResponse>);
  @override
  _i2.ResponseFuture<_i6.GetLinearAccelerationResponse> getLinearAcceleration(
    _i6.GetLinearAccelerationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearAcceleration,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetLinearAccelerationResponse>(
          this,
          Invocation.method(
            #getLinearAcceleration,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetLinearAccelerationResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [RobotServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobotServiceClient extends _i1.Mock
    implements _i9.RobotServiceClient {
  MockRobotServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i10.GetOperationsResponse> getOperations(
    _i10.GetOperationsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetOperationsResponse>);
  @override
  _i2.ResponseFuture<_i10.GetSessionsResponse> getSessions(
    _i10.GetSessionsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetSessionsResponse>);
  @override
  _i2.ResponseFuture<_i10.ResourceNamesResponse> resourceNames(
    _i10.ResourceNamesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceNames,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.ResourceNamesResponse>);
  @override
  _i2.ResponseFuture<_i10.ResourceRPCSubtypesResponse> resourceRPCSubtypes(
    _i10.ResourceRPCSubtypesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceRPCSubtypes,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.ResourceRPCSubtypesResponse>);
  @override
  _i2.ResponseFuture<_i10.CancelOperationResponse> cancelOperation(
    _i10.CancelOperationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.CancelOperationResponse>);
  @override
  _i2.ResponseFuture<_i10.BlockForOperationResponse> blockForOperation(
    _i10.BlockForOperationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockForOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.BlockForOperationResponse>);
  @override
  _i2.ResponseFuture<_i10.DiscoverComponentsResponse> discoverComponents(
    _i10.DiscoverComponentsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverComponents,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.DiscoverComponentsResponse>);
  @override
  _i2.ResponseFuture<_i10.FrameSystemConfigResponse> frameSystemConfig(
    _i10.FrameSystemConfigRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #frameSystemConfig,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.FrameSystemConfigResponse>);
  @override
  _i2.ResponseFuture<_i10.TransformPoseResponse> transformPose(
    _i10.TransformPoseRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPose,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.TransformPoseResponse>);
  @override
  _i2.ResponseFuture<_i10.TransformPCDResponse> transformPCD(
    _i10.TransformPCDRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPCD,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.TransformPCDResponse>);
  @override
  _i2.ResponseFuture<_i10.GetStatusResponse> getStatus(
    _i10.GetStatusRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetStatusResponse>);
  @override
  _i2.ResponseStream<_i10.StreamStatusResponse> streamStatus(
    _i10.StreamStatusRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<_i10.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<_i10.StreamStatusResponse>);
  @override
  _i2.ResponseFuture<_i10.StopAllResponse> stopAll(
    _i10.StopAllRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAll,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.StopAllResponse>);
  @override
  _i2.ResponseFuture<_i10.StartSessionResponse> startSession(
    _i10.StartSessionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.StartSessionResponse>);
  @override
  _i2.ResponseFuture<_i10.SendSessionHeartbeatResponse> sendSessionHeartbeat(
    _i10.SendSessionHeartbeatRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSessionHeartbeat,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.SendSessionHeartbeatResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [SensorsServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorsServiceClient extends _i1.Mock
    implements _i11.SensorsServiceClient {
  MockSensorsServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i12.GetSensorsResponse> getSensors(
    _i12.GetSensorsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensors,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i12.GetSensorsResponse>(
          this,
          Invocation.method(
            #getSensors,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i12.GetSensorsResponse>);
  @override
  _i2.ResponseFuture<_i12.GetReadingsResponse> getReadings(
    _i12.GetReadingsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadings,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i12.GetReadingsResponse>(
          this,
          Invocation.method(
            #getReadings,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i12.GetReadingsResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [CameraServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraServiceClient extends _i1.Mock
    implements _i13.CameraServiceClient {
  MockCameraServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i14.GetImageResponse> getImage(
    _i14.GetImageRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetImageResponse>(
          this,
          Invocation.method(
            #getImage,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetImageResponse>);
  @override
  _i2.ResponseFuture<_i15.HttpBody> renderFrame(
    _i14.RenderFrameRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renderFrame,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i15.HttpBody>(
          this,
          Invocation.method(
            #renderFrame,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i15.HttpBody>);
  @override
  _i2.ResponseFuture<_i14.GetPointCloudResponse> getPointCloud(
    _i14.GetPointCloudRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPointCloud,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetPointCloudResponse>(
          this,
          Invocation.method(
            #getPointCloud,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetPointCloudResponse>);
  @override
  _i2.ResponseFuture<_i14.GetPropertiesResponse> getProperties(
    _i14.GetPropertiesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetPropertiesResponse>(
          this,
          Invocation.method(
            #getProperties,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetPropertiesResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [StreamServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamServiceClient extends _i1.Mock
    implements _i16.StreamServiceClient {
  MockStreamServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i17.ListStreamsResponse> listStreams(
    _i17.ListStreamsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listStreams,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.ListStreamsResponse>(
          this,
          Invocation.method(
            #listStreams,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.ListStreamsResponse>);
  @override
  _i2.ResponseFuture<_i17.AddStreamResponse> addStream(
    _i17.AddStreamRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStream,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.AddStreamResponse>(
          this,
          Invocation.method(
            #addStream,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.AddStreamResponse>);
  @override
  _i2.ResponseFuture<_i17.RemoveStreamResponse> removeStream(
    _i17.RemoveStreamRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStream,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.RemoveStreamResponse>(
          this,
          Invocation.method(
            #removeStream,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.RemoveStreamResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [ClientChannelBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientChannelBase extends _i1.Mock implements _i18.ClientChannelBase {
  MockClientChannelBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i4.ConnectionState> get onConnectionStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectionStateChanged),
        returnValue: _i8.Stream<_i4.ConnectionState>.empty(),
      ) as _i8.Stream<_i4.ConnectionState>);
  @override
  _i8.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i4.ClientConnection createConnection() => (super.noSuchMethod(
        Invocation.method(
          #createConnection,
          [],
        ),
        returnValue: _FakeClientConnection_3(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
      ) as _i4.ClientConnection);
  @override
  _i8.Future<_i4.ClientConnection> getConnection() => (super.noSuchMethod(
        Invocation.method(
          #getConnection,
          [],
        ),
        returnValue:
            _i8.Future<_i4.ClientConnection>.value(_FakeClientConnection_3(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
      ) as _i8.Future<_i4.ClientConnection>);
  @override
  _i3.ClientCall<Q, R> createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests,
    _i2.CallOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCall,
          [
            method,
            requests,
            options,
          ],
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
}
