// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/analytics/service/analytics_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/data/analytics/data_sink/analytics_data_sink.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnalyticsDataSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsDataSink extends _i1.Mock implements _i2.AnalyticsDataSink {
  MockAnalyticsDataSink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logEvent({
    required String? name,
    Map<String, Object?>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [],
          {
            #name: name,
            #parameters: parameters,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
