// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/resource/service/resource_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/data/resource/data_source/resource_api_data_source.dart' as _i3;
import 'package:viam_marine/data/resource/mapper/viam_resource_name_to_viam_app_resource_name_mapper.dart' as _i7;
import 'package:viam_marine/domain/resource/model/resource_filters.dart' as _i6;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart' as _i2;
import 'package:viam_sdk/viam_sdk.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViamAppResourceName_0 extends _i1.SmartFake implements _i2.ViamAppResourceName {
  _FakeViamAppResourceName_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ResourceDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockResourceDataSource extends _i1.Mock implements _i3.ResourceDataSource {
  MockResourceDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ViamResourceName>> getResourceNames(
    _i6.ViamAppResourceSubtypeFilter? subtype,
    _i6.ViamAppResourceNameFilter? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getResourceNames,
          [
            subtype,
            name,
          ],
        ),
        returnValue: _i4.Future<List<_i5.ViamResourceName>>.value(<_i5.ViamResourceName>[]),
      ) as _i4.Future<List<_i5.ViamResourceName>>);
}

/// A class which mocks [ViamResourceNameToViamAppResourceNameMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamResourceNameToViamAppResourceNameMapper extends _i1.Mock
    implements _i7.ViamResourceNameToViamAppResourceNameMapper {
  MockViamResourceNameToViamAppResourceNameMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ViamAppResourceName call(_i5.ViamResourceName? dto) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [dto],
        ),
        returnValue: _FakeViamAppResourceName_0(
          this,
          Invocation.method(
            #call,
            [dto],
          ),
        ),
      ) as _i2.ViamAppResourceName);
}
