// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/domain/movement/usecase/get_linear_velocity_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/movement/model/viam_app_linear_velocity.dart' as _i3;
import 'package:viam_marine/domain/movement/model/viam_app_position.dart' as _i2;
import 'package:viam_marine/domain/movement/service/movement_service.dart' as _i4;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViamAppPosition_0 extends _i1.SmartFake implements _i2.ViamAppPosition {
  _FakeViamAppPosition_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViamAppLinearVelocity_1 extends _i1.SmartFake implements _i3.ViamAppLinearVelocity {
  _FakeViamAppLinearVelocity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ViamAppMovementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppMovementService extends _i1.Mock implements _i4.ViamAppMovementService {
  MockViamAppMovementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ViamAppPosition> getPosition(_i6.ViamAppResourceName? resourceName) => (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [resourceName],
        ),
        returnValue: _i5.Future<_i2.ViamAppPosition>.value(_FakeViamAppPosition_0(
          this,
          Invocation.method(
            #getPosition,
            [resourceName],
          ),
        )),
      ) as _i5.Future<_i2.ViamAppPosition>);
  @override
  _i5.Future<_i3.ViamAppLinearVelocity> getLinearVelocity(_i6.ViamAppResourceName? resourceName) => (super.noSuchMethod(
        Invocation.method(
          #getLinearVelocity,
          [resourceName],
        ),
        returnValue: _i5.Future<_i3.ViamAppLinearVelocity>.value(_FakeViamAppLinearVelocity_1(
          this,
          Invocation.method(
            #getLinearVelocity,
            [resourceName],
          ),
        )),
      ) as _i5.Future<_i3.ViamAppLinearVelocity>);
}
