// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/data/camera/service/camera_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_webrtc/flutter_webrtc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/data/camera/data_source/camera_api_data_source.dart'
    as _i4;
import 'package:viam_marine/app/data/camera/mapper/viam_camera_data_to_viam_app_camera_data_mapper.dart'
    as _i7;
import 'package:viam_marine/app/domain/camera/model/viam_app_camera_data.dart'
    as _i3;
import 'package:viam_marine/sdk/viam_sdk.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeViamCameraFrameData_0 extends _i1.SmartFake
    implements _i2.ViamCameraFrameData {
  _FakeViamCameraFrameData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViamAppCameraData_1 extends _i1.SmartFake
    implements _i3.ViamAppCameraData {
  _FakeViamAppCameraData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CameraDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraDataSource extends _i1.Mock implements _i4.CameraDataSource {
  MockCameraDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ViamCameraFrameData> getCameraData(String? cameraName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCameraData,
          [cameraName],
        ),
        returnValue: _i5.Future<_i2.ViamCameraFrameData>.value(
            _FakeViamCameraFrameData_0(
          this,
          Invocation.method(
            #getCameraData,
            [cameraName],
          ),
        )),
      ) as _i5.Future<_i2.ViamCameraFrameData>);
  @override
  _i5.Stream<_i6.MediaStream> subscribeToCameraStream() => (super.noSuchMethod(
        Invocation.method(
          #subscribeToCameraStream,
          [],
        ),
        returnValue: _i5.Stream<_i6.MediaStream>.empty(),
      ) as _i5.Stream<_i6.MediaStream>);
  @override
  _i5.Future<void> getCameraVideo(String? cameraName) => (super.noSuchMethod(
        Invocation.method(
          #getCameraVideo,
          [cameraName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ViamCameraDataToViamAppCameraDataMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamCameraDataToViamAppCameraDataMapper extends _i1.Mock
    implements _i7.ViamCameraDataToViamAppCameraDataMapper {
  MockViamCameraDataToViamAppCameraDataMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ViamAppCameraData call(_i2.ViamCameraFrameData? cameraData) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [cameraData],
        ),
        returnValue: _FakeViamAppCameraData_1(
          this,
          Invocation.method(
            #call,
            [cameraData],
          ),
        ),
      ) as _i3.ViamAppCameraData);
}
