// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/domain/permissions/usecase/request_camera_permission_status_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i4;
import 'package:viam_marine/app/domain/permissions/service/permissions_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PermissionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsService extends _i1.Mock
    implements _i2.PermissionsService {
  MockPermissionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PermissionStatus> getCameraPermissionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCameraPermissionStatus,
          [],
        ),
        returnValue:
            _i3.Future<_i4.PermissionStatus>.value(_i4.PermissionStatus.denied),
      ) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestCameraPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestCameraPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i4.PermissionStatus>.value(_i4.PermissionStatus.denied),
      ) as _i3.Future<_i4.PermissionStatus>);
}
