// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/locations/cubit/locations_page_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/app_viam/model/viam_app_location.dart'
    as _i4;
import 'package:viam_marine/domain/app_viam/model/viam_app_robot.dart' as _i6;
import 'package:viam_marine/domain/app_viam/usecase/get_location_id_use_case.dart'
    as _i14;
import 'package:viam_marine/domain/app_viam/usecase/get_locations_use_case.dart'
    as _i2;
import 'package:viam_marine/domain/app_viam/usecase/get_robot_id_use_case.dart'
    as _i13;
import 'package:viam_marine/domain/app_viam/usecase/get_robots_use_case.dart'
    as _i5;
import 'package:viam_marine/domain/app_viam/usecase/set_location_id_use_case.dart'
    as _i15;
import 'package:viam_marine/domain/app_viam/usecase/set_robot_id_use_case.dart'
    as _i12;
import 'package:viam_marine/domain/boat/model/viam_boat.dart' as _i11;
import 'package:viam_marine/domain/boat/usecase/add_new_boat_use_case.dart'
    as _i9;
import 'package:viam_marine/domain/boat/usecase/get_boats_use_case.dart'
    as _i10;
import 'package:viam_marine/domain/viam/model/robot_address_config.dart'
    as _i17;
import 'package:viam_marine/domain/viam/usecase/connect_to_robot_use_case.dart'
    as _i7;
import 'package:viam_marine/domain/viam/usecase/get_robot_address_use_case.dart'
    as _i16;
import 'package:viam_marine/domain/viam/usecase/get_token_or_null_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetLocationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationsUseCase extends _i1.Mock
    implements _i2.GetLocationsUseCase {
  MockGetLocationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamAppLocation>> call(String? organizationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [organizationId],
        ),
        returnValue: _i3.Future<List<_i4.ViamAppLocation>>.value(
            <_i4.ViamAppLocation>[]),
      ) as _i3.Future<List<_i4.ViamAppLocation>>);
}

/// A class which mocks [GetRobotsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRobotsUseCase extends _i1.Mock implements _i5.GetRobotsUseCase {
  MockGetRobotsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.ViamAppRobot>> call(String? locationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [locationId],
        ),
        returnValue:
            _i3.Future<List<_i6.ViamAppRobot>>.value(<_i6.ViamAppRobot>[]),
      ) as _i3.Future<List<_i6.ViamAppRobot>>);
}

/// A class which mocks [ConnectToRobotUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectToRobotUseCase extends _i1.Mock
    implements _i7.ConnectToRobotUseCase {
  MockConnectToRobotUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? url,
    required int? port,
    required bool? secure,
    required bool? disableWebRtc,
    String? secret,
    String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #url: url,
            #port: port,
            #secure: secure,
            #disableWebRtc: disableWebRtc,
            #secret: secret,
            #accessToken: accessToken,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetTokenOrNullUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTokenOrNullUseCase extends _i1.Mock
    implements _i8.GetTokenOrNullUseCase {
  MockGetTokenOrNullUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [AddNewBoatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewBoatUseCase extends _i1.Mock implements _i9.AddNewBoatUseCase {
  MockAddNewBoatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call({
    required String? id,
    String? photoPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #id: id,
            #photoPath: photoPath,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetBoatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBoatsUseCase extends _i1.Mock implements _i10.GetBoatsUseCase {
  MockGetBoatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.ViamBoat>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i11.ViamBoat>>.value(<_i11.ViamBoat>[]),
      ) as _i3.Future<List<_i11.ViamBoat>>);
}

/// A class which mocks [SetRobotIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetRobotIdUseCase extends _i1.Mock implements _i12.SetRobotIdUseCase {
  MockSetRobotIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetRobotIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRobotIdUseCase extends _i1.Mock implements _i13.GetRobotIdUseCase {
  MockGetRobotIdUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetLocationIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLocationIdUseCase extends _i1.Mock
    implements _i14.GetLocationIdUseCase {
  MockGetLocationIdUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SetLocationIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetLocationIdUseCase extends _i1.Mock
    implements _i15.SetLocationIdUseCase {
  MockSetLocationIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetRobotAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRobotAddressUseCase extends _i1.Mock
    implements _i16.GetRobotAddressUseCase {
  MockGetRobotAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call(_i17.RobotAddressConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [config],
        ),
        returnValue: '',
      ) as String);
}
