// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/domain/sensors/usecase/get_sensor_data_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/domain/resource/model/viam_app_resource_name.dart' as _i5;
import 'package:viam_marine/domain/sensor/model/viam_app_sensor_readings.dart' as _i4;
import 'package:viam_marine/domain/sensor/service/sensor_service_impl.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ViamAppSensorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamAppSensorService extends _i1.Mock implements _i2.ViamAppSensorService {
  MockViamAppSensorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ViamAppSensorReadings>> getSensorData(List<_i5.ViamAppResourceName>? resourceNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensorData,
          [resourceNames],
        ),
        returnValue: _i3.Future<List<_i4.ViamAppSensorReadings>>.value(<_i4.ViamAppSensorReadings>[]),
      ) as _i3.Future<List<_i4.ViamAppSensorReadings>>);
}
