// Mocks generated by Mockito 5.3.2 from annotations
// in viam_marine/test/unit_test/presentation/page/splash/cubit/splash_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_marine/app/domain/boat/model/viam_boat.dart' as _i5;
import 'package:viam_marine/app/domain/boat/usecase/get_boats_use_case.dart'
    as _i3;
import 'package:viam_marine/app/domain/boat/usecase/get_current_boat_id_use_case.dart'
    as _i2;
import 'package:viam_marine/app/domain/viam/usecase/viam_connect_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetCurrentBoatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentBoatIdUseCase extends _i1.Mock
    implements _i2.GetCurrentBoatIdUseCase {
  MockGetCurrentBoatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetBoatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBoatsUseCase extends _i1.Mock implements _i3.GetBoatsUseCase {
  MockGetBoatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ViamBoat>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ViamBoat>>.value(<_i5.ViamBoat>[]),
      ) as _i4.Future<List<_i5.ViamBoat>>);
}

/// A class which mocks [ViamConnectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockViamConnectUseCase extends _i1.Mock
    implements _i6.ViamConnectUseCase {
  MockViamConnectUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call({
    required String? url,
    required int? port,
    required bool? secure,
    required bool? disableWebRtc,
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #url: url,
            #port: port,
            #secure: secure,
            #disableWebRtc: disableWebRtc,
            #secret: secret,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
